title: Hello world! I'm RoryHay.es!
description: > # this means to ignore newlines until "baseurl:"
  A personal blog and portfolio for Software & Computer Engineer Rory Hayes.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://roryhay.es" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Toast message settings
toast-message: Rory is actively looking for work and available for hire!
toast-color: 2ECC40
toast-icon: far fa-check-circle


# Author Settings
author: Rory Hayes # add your name
author-img: rory-hayes.png # add your photo
about-author1: Software & Computer Enginner # add description
about-author2: Available for Hire! # add description
about-author3: LED/Laser Lighting Wizard # add description
about-author4: Right-to-Repair Evangelist # add description

# Social
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rorosaurus # add your Github handle
social-linkedin: roryhayes # add your Linkedin handle
social-discord: 181592072023703552 # add your discord user ID
social-email: roryohayes@gmail.com # add your Email address
social-vcard: "/assets/files/Rory Hayes.vcf" # add your vcard link
social-resume: "https://github.com/rorosaurus/resume" # add your resume link

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  posts:
    output: true
    permalink: /blog/:title