title: Hello, world! I'm Rory Hayes
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rory O Hayes # add your name
author-img: rory-hayes.jpg # add your photo
about-author: I am a Software & Computer Engineer with a strong affinity for LED art! # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rorosaurus # add your Github handle
social-linkedin: roryhayes # add your Linkedin handle
social-discord: 181592072023703552 # add your discord user ID
social-email: roryohayes@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
