title: Hello world! I'm RoryHay.es!
description: > # this means to ignore newlines until "baseurl:"
  A personal blog and portfolio for Software & Computer Engineer Rory Hayes.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://roryhay.es" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Toast message settings
toast-message-background: 99ff81
toast-message: Rory is available for hire!
toast-icon-background: 2bb339
toast-icon: far fa-check-circle
toast-link: "https://rorosaurus.github.io/resume/Rory%20O%20Hayes%20-%20Resume.pdf"


# Author Settings
author: Rory Hayes # add your name
author-img: rory-hayes.jpg # add your photo
author-subtitle: Software & Computer Engineer # add description

about-author-typing: true # exchange about author text with alts using typing effect
about-author-typing-delay: 7000

about-author1: Maker & Tinkerer # add description
about-author1-alt: Retro Electronics Modder # add description

about-author2: Right-to-Repair Evangelist # add description
about-author2-alt: PCB Design & Distributed Art # add description

about-author3: LED & Laser Lighting Wizard # add description
about-author3-alt: Infosec / Privacy / Rights Advocate # add description

# Social
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
# social-calendar: "/calendar" # add your public calendar link
social-github: rorosaurus # add your Github handle
social-linkedin: roryhayes # add your Linkedin handle
social-discord: 181592072023703552 # add your discord user ID
social-email: roryohayes@gmail.com # add your Email address
social-vcard: "/assets/files/Rory Hayes.vcf" # add your vcard link
social-resume: "https://rorosaurus.github.io/resume/Rory%20O%20Hayes%20-%20Resume.pdf" # add your resume link

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  posts:
    output: true
    permalink: /blog/:title